---
- name: line in playbook
  hosts: all
  become: true
  tasks:
    - name: line in file
      lineinfile:
        path: /root/.ssh/authorized_keys
        line: 'hello kjnregjknerkgn dngkjdnfgjnendgjkndiurg jnrgkjehriugh rkjgnkerhugteiut nkjrdgnkerhtie ndgjnrhgn ejnferjht djrnteurt djnfjreng nderjfnerjngjng ndjnfgertgn djrngfekjrnt kdjngkjrne'
        state: present
